# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv'
df = pd.read_csv(url)
df.head()

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

### Step 4. See the first 10 entries

In [3]:
df.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [4]:
df.drop(columns=['Unnamed: 0', 'Id'], inplace=True)
df.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### What year has the highest number of baby names in the dataset?

In [7]:
int(df.groupby('Year').sum().idxmax()['Name']) #just want the one for name

2010

### Step 6. Is there more male or female names in the dataset?

In [12]:
num_fem = int(df['Gender'].value_counts()['F'])
num_male = int(df['Gender'].value_counts()['M'])
if num_fem >= num_male:
    print("More females")
else:
    print("More males")

More females

### Step 7. Group the dataset by name and assign to names

In [ ]:
names = df.groupby('Name', as_index=True)[['Count']].sum() #to get it as a dataframe, added the extra brackets around 'Count'

names.sort_values('Count', ascending=False).head() #if you used a series, wouldn't need the 'Count' because would be autosorted

           Count
Name
Jacob     242874
Emma      214852
Michael   214405
Ethan     209277
Isabella  204798

### Step 8. How many different names exist in the dataset?

In [16]:
len(names) #all names unique alr since we grouped by it, so just the length

17632

### Step 9. What is the name with most occurrences?

In [18]:
#names.groupby('Name').sum().idxmax()['Count'] don't need another groupBy cuz alr grouped by it
names['Count'].idxmax()

'Jacob'

### Step 10. How many different names have the least occurrences?

In [29]:
names.head()

         Count
Name
Aaban       12
Aadan       23
Aadarsh      5
Aaden     3426
Aadhav       6

In [30]:
#print((names[names['Count'] == names['Count'].min()]).sum()) this one is wrong, actually adds those counts
print(len(names[names['Count'] == names['Count'].min()]))


(names['Count'] == names['Count'].min()).sum() #this one correct, actually sums the bools

2578

np.int64(2578)

### Step 11. What is the median name occurrence?

In [31]:
names['Count'].median()

np.float64(49.0)

### Step 12. What is the standard deviation of names?

In [35]:
int(names['Count'].std())

11006

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [36]:
names.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000